name: Secrets Scanner action
on: push
jobs:
  TruffleHog:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # ref: ${{ github.head_ref }} // necessary for pull request workflow trigger
      - name: trufflehog-actions-scan
        uses: edplato/trufflehog-actions-scan@master
        continue-on-error: true

