name: Secrets Scanner action
on: [pull_request,push]
jobs:
  TruffleHog:
    runs-on: ubuntu-latest

    steps:
     - name: code checkout
       uses: actions/checkout@v3
     - name: Secret Scanning
       uses: kams-mash/gh-secrets-scanner-action@master
       continue-on-error: true

